# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '项目分类' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Reachability', '~> 3.2'
pod 'AFNetworking', '~> 3.0.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'Masonry', '~> 0.6.4'
pod 'IQKeyboardManager', '~> 4.0.0'
pod 'SVProgressHUD'
pod 'MJExtension', '~> 3.0.10'
pod 'ReactiveCocoa', '~> 2.5'

  # Pods for 项目分类

  target '项目分类Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '项目分类UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
